### ISSUE TITLE
Design Ideas

### ISSUE THREAD

**Issue by riyasoganii** [intermine/bluegenes-ux-ideas#2]
Hey all! Until we work our way through the user research angle, I thought I'd create an issue relating to the overall design and layout of the website, where we can get ideas through our own perusal of the site and hence post suggestions for the improvement of the same!
I've created a list of issues/ideas and design solutions, please feel free to add more!
[Design proposal-bluegenes.pdf](https://github.com/intermine/bluegenes-ux-ideas/files/4349093/Design.proposal-bluegenes.pdf)

**Comment by yochannah** [comment]
@riyasoganii these are some really great suggestions and perfectly in line with the type of thing we are looking for ✨ Steps onwards from here could be: 

- look for more issues like this and plan how you would work fixing them over the outreachy period (would require being comfortable writing hiccup, less, and possibly learning a bit of clojure) OR
- plan an "investigation" period with user interviews as well as using UX heuristics , and then coming up with sets of recommendations for the InterMine team to implement
- or maybe a mix of both or some othe creative idea you might have :)

**Comment by riyasoganii** [comment]
@yochannah Would those ideas be for me to include in the final proposal? Or do I continue the discussion through this issue?

**Comment by riyasoganii** [comment]
@yochannah I've prepared some ideas of what my above proposed desktop website design would look like on a mobile- please have a look!
EDIT: The intermine logo would be replaced with a 'Bluegenes' logo once available.
![Select text (3)](https://user-images.githubusercontent.com/59031971/78359949-a2512e80-75d3-11ea-84d3-d10f36ec3a62.png)
![Select text (4)](https://user-images.githubusercontent.com/59031971/78360002-b9901c00-75d3-11ea-9eb7-06a081e8efa8.png)

**Comment by mfonobongd** [comment]
> Hey all! Until we work our way through the user research angle, I thought I'd create an issue relating to the overall design and layout of the website, where we can get ideas through our own perusal of the site and hence post suggestions for the improvement of the same!
> I've created a list of issues/ideas and design solutions, please feel free to add more!
> [Design proposal-bluegenes.pdf](https://github.com/intermine/bluegenes-ux-ideas/files/4349093/Design.proposal-bluegenes.pdf)

This is a great Idea @riyasoganii  I also suggest that before we dive into the design, we need to write out user stories which would help us create a user flow for the platform and then conduct user interviews. I believe this would help use approach the redesign with the User Empathy. And not just to design a site but a usable website with it's mobile responsiveness.

**Comment by yochannah** [comment]
hey all - I'm closing this issue now as the Outreachy internship period has started. Thanks everyone for the delightful discussions and fabulous collaborations! 🚀 ❤️
