### ISSUE TITLE
UX/UI Changes to website

### ISSUE THREAD

**Issue by roshnidesigns** [intermine/bluegenes-ux-ideas#4]
I've gone thoroughly through the website and found some issues related usability and aesthetics. I hope to improve overall user experience of the website and hence proposed some of the changes:
These are some light changes on existing website design as @yochannah told no heavy changes are required as for now. 
Feedbacks appreciated.

**Comment by tinycosmos** [comment]
<img width="3946" alt="home_issues" src="https://user-images.githubusercontent.com/45714224/77225369-7033db80-6b94-11ea-95a9-5d37f5944a63.png">
<img width="3946" alt="home_redesign" src="https://user-images.githubusercontent.com/45714224/77225374-775ae980-6b94-11ea-920d-d7dde5b6471f.png">

**Comment by roshnidesigns** [comment]
[RedesignConceptby_RoshniPrajapati.pdf](https://github.com/intermine/bluegenes-ux-ideas/files/4365048/RedesignConceptby_RoshniPrajapati.pdf)
Here are some of the major issues that I noticed, but i also have some new design concepts if you say i may mention those too.

**Comment by ss200598** [comment]
Hey @tinycosmos can I contribute to this one? I have some ideas.

**Comment by roshnidesigns** [comment]
@ss200598 yeah sure go ahead!

**Comment by ss200598** [comment]
![Untitled](https://user-images.githubusercontent.com/37297898/77303595-3809d580-6d19-11ea-91d7-a2bb5c0f5766.png)
![Untitled1](https://user-images.githubusercontent.com/37297898/77303597-3a6c2f80-6d19-11ea-82a7-7f79eb0bfde9.png)

**Comment by ss200598** [comment]
I m not sure which logo should come in the center. But the empty space is not looking good.

**Comment by roshnidesigns** [comment]
> I m not sure which logo should come in the center. But the empty space is not looking good.

Yeah you're right! empty space sure doesn't looks good, and i don't think putting logo in the space is much of an appreciated idea. Have you gone through my proposal, i mentioned there that if possible we can add an extra 'div' or bar at the top of navigation bar where logo could be placed and as for the empty space I have mentioned the ideas it can be occupied with.
Well if you have any ideas other than the logo please do tell, thanks :)
