### ISSUE TITLE
Blue genes logo design- Manishita Choudhary

### ISSUE THREAD

**Issue by manishita24** [intermine/bluegenes-ux-ideas#6]
Here is a logo design for the genes website:

![crop](https://user-images.githubusercontent.com/60927308/78689864-6b9d5000-7914-11ea-8bec-1b78d0c10403.jpg)

**Comment by yochannah** [comment]
This would make a really nice hex sticker - http://hexb.in/sticker.html

**Comment by manishita24** [comment]
> This would make a really nice hex sticker - http://hexb.in/sticker.html

haha 😂 yes for sure 😍💯

**Comment by yochannah** [comment]
hey all - I'm closing this issue now as the Outreachy internship period has started. Thanks everyone for the delightful discussions and fabulous collaborations! 🚀 ❤️
