### ISSUE TITLE
Design proposal for bluegenes loading page - Manishita choudhary

### ISSUE THREAD

**Issue by manishita24** [intermine/bluegenes-ux-ideas#7]
The current loading page is very simple and does not go along with the color scheme of intermine ie green, black and grey.
This is a new design prototype for the loading page which gives the page a better interactive and attractive feel while keeping it minimal.

Here is an example gif:
<img src="https://user-images.githubusercontent.com/60927308/78893772-80e7bb00-7a89-11ea-893b-c726eccecd4a.gif" width="615" height="315">

this prototype is created in invision and can be viewed here: https://projects.invisionapp.com/prototype/ck8sqg2a1006hqz01gds7x1ep/play

**Comment by heralden** [comment]
Sorry for the late follow-up! I like the idea of using the Intermine logo as a loader, but I don't think the text below and above it fit well as they are currently. We might not need to include the text "InterMine", but we'll need "Loading" to let the user know what they're seeing.

@yochannah What do you think?

**Comment by manishita24** [comment]
> Sorry for the late follow-up! I like the idea of using the Intermine logo as a loader, but I don't think the text below and above it fit well as they are currently. We might not need to include the text "InterMine", but we'll need "Loading" to let the user know what they're seeing.
> 
> @yochannah What do you think?

yes i agree. The text "intermine" can be removed from it.

**Comment by yochannah** [comment]
hey all - I'm closing this issue now as the Outreachy internship period has started. Thanks everyone for the delightful discussions and fabulous collaborations! 🚀 ❤️
